default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>


development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] + '_development' %>
  
test:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] + '_test' %>

# production:
#   primary: &primary_production
#     <<: *default
#     database: back_end_ruby_production
#     username: back_end_ruby
#     password: <%= ENV["BACK_END_RUBY_DATABASE_PASSWORD"] %>
#   cache:
#     <<: *primary_production
#     database: back_end_ruby_production_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *primary_production
#     database: back_end_ruby_production_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *primary_production
#     database: back_end_ruby_production_cable
#     migrations_paths: db/cable_migrate
